<?php

/**
 * @file
 * Contains social_metatag_preview.module.
 */

declare(strict_types=1);

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;
use Drupal\media\MediaInterface;

/**
 * Implements hook_help().
 */
function social_metatag_preview_help(string $route_name, RouteMatchInterface $route_match): string {
  switch ($route_name) {
    case 'help.page.social_metatag_preview':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Metatag interface for editing Open Graph (Facebook), Twitter Cards, and search engine markup - including social sharing images') . '</p>';
      return $output;
  }

  return '';
}

/**
 * Implements hook_theme().
 */
function social_metatag_preview_theme($existing, $type, $theme, $path): array {
  return [
    'social_metatag_preview' => [
      'variables' => [
        'preview_type' => 'search',
        'meta' => NULL,
        'url' => NULL,
        'host' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function social_metatag_preview_token_info(): array {
  $info['types']['social-metatag-preview'] = [
    'name' => t('Social Metatag Preview'),
    'description' => t('Tokens for Social Metatag Preview.'),
  ];

  $info['tokens']['social-metatag-preview']['image-src'] = [
    'name' => t('Image src'),
    'description' => t('Displays a social image url. Requires an image media id.'),
    'dynamic' => TRUE,
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 */
function social_metatag_preview_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata): array {
  $replacements = [];

  if ($type !== 'social-metatag-preview') {
    return $replacements;
  }

  $token_service = \Drupal::token();
  $image_src_tokens = $token_service->findWithPrefix($tokens, 'image-src');
  if (!$image_src_tokens) {
    return $replacements;
  }

  $entity_type_manager = \Drupal::entityTypeManager();
  $image_style = $entity_type_manager
    ->getStorage('image_style')
    ->load('social_metatag_preview_image');

  if (!$image_style) {
    return $replacements;
  }

  $media_storage = $entity_type_manager->getStorage('media');

  foreach ($image_src_tokens as $mid => $original) {
    $replacement = '';

    $media = $media_storage->load($mid);
    if ($media instanceof MediaInterface) {
      $bundle_entity = $media->bundle->entity ?? NULL;
      if ($bundle_entity) {
        $source_field_definition = $media->getSource()->getSourceFieldDefinition($bundle_entity);
        $source_field_name = $source_field_definition?->getName();
        $file_entity = $source_field_name ? ($media->{$source_field_name}->entity ?? NULL) : NULL;
        if ($file_entity instanceof FileInterface) {
          $replacement = $image_style->buildUrl($file_entity->getFileUri());
        }
      }
    }

    $replacements[$original] = $replacement;
  }

  return $replacements;
}
